namespace BuyTheBoat.Domain;

// One movement of money into (or, when negative, back out of) a fund jar on
// a specific day. "'earmark' and 'earmark event' mean the same thing in this
// project. Each one occurs once on a specific day and moves a certain amount
// of money around." (class documentation.ods). Positive ExpectedAmount moves
// money INTO the jar; negative pulls it back into free balance.
//
// Repeated = generated by an EarMarkPattern's rrule, amount fixed by the
// pattern. Isolated = a one-off, manual or system-generated. At most one of
// each per finance id per day — a second isolated earmark on the same
// finance_id/day merges into the first rather than creating a new event.
public sealed record EarMarkEvent
{
    // The goal/bill this earmark is saving for; null = the safety cushion.
    public required int? FinanceId { get; init; }

    // "All earmarks need a date. Having a date lets us create earmarks
    // manually whenever we want."
    public required DateOnly EarmarkDate { get; init; }

    public required bool RepeatedEarmark { get; init; }

    public required decimal ExpectedAmount { get; init; }

    // Isolated earmarks only (null on repeated ones): the portion the USER
    // explicitly entered, preserved so the system can later undo its own
    // implicit adjustments without losing the user's intent
    // (reverse_implicit_earmarks in the documented model). 0 on purely
    // system-generated events.
    //
    // DIVERGENCE(positive-implicit): the original design only ever created
    // implicit isolated earmarks with NEGATIVE amounts — deallocation-day
    // give-backs triggered by actual transactions. It also creates
    // POSITIVE implicit events to refill the safety cushion toward its
    // target. (Mandatory bills were once auto-reserved this way too; they
    // now reserve through their own savings plan, created when the bill is
    // saved.)
    public required decimal? ExplicitAmount { get; init; }

    // How much actually moved once the day occurred — computable only from
    // ActualTransactions, per the documented cascade ("one of the last
    // things a cascade update computes").
    // ASSUMED-PAIRING(actual-amount): always null for now; real values
    // arrive with transaction import.
    public decimal? ActualAmount { get; init; }
}
